# Generated by Django 5.1.6 on 2025-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('last_requested', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('method', 'endpoint')},
            },
        ),
    ]
