# Generated by Django 5.1.6 on 2025-03-10 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_examination_examined_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_brand', models.CharField(max_length=100)),
                ('frame_model', models.CharField(max_length=100)),
                ('frame_color', models.CharField(max_length=50)),
                ('frame_quantity', models.PositiveIntegerField(default=1)),
                ('frame_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lens_brand', models.CharField(max_length=100)),
                ('lens_type', models.CharField(max_length=100)),
                ('lens_material', models.CharField(max_length=100)),
                ('lens_coating', models.CharField(max_length=100)),
                ('lens_quantity', models.PositiveIntegerField(default=1)),
                ('lens_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fitting_instructions', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('booked_by', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'M-Pesa'), ('Card', 'Credit Card'), ('Bank', 'Bank Transfer'), ('Insurance', 'Insurance')], default='Cash', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mpesa', 'M-Pesa'), ('Card', 'Credit Card'), ('Bank', 'Bank Transfer'), ('Insurance', 'Insurance')], max_length=10, null=True)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Pending', max_length=15)),
                ('balance_payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Pending', max_length=15)),
                ('order_paid', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Pending', max_length=15)),
                ('mpesa_transaction_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='clients.examination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
