# Generated by Django 5.1.6 on 2025-03-10 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='served_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
