# Generated by Django 5.1.6 on 2025-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_sales_served_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='booked_for_sales',
            field=models.BooleanField(default=False),
        ),
    ]
