# Generated by Django 5.1.6 on 2025-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_examination_booked_for_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
