# Generated by Django 5.1.6 on 2025-03-14 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_branch_client_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
