# Generated by Django 5.1.6 on 2025-03-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_branch_alter_branch_id'),
        ('clients', '0007_client_branch'),
    ]

    operations = [
    ]
