# Generated by Django 5.1.6 on 2025-03-14 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_merge_20250314_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.CharField(default=datetime.datetime(2025, 3, 14, 13, 7, 53, 76489, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
