# Generated by Django 5.1.6 on 2025-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('receptionist', 'Receptionist'), ('optometrist', 'Optometrist')], default='staff', max_length=20),
        ),
    ]
